site_name: Celesta
site_url: https://astridyz.github.io/Celesta/

repo_name: astridyz/Celesta
repo_url: https://github.com/astridyz/Celesta

theme:
  name: material
  custom_dir: docs/assets/overrides

  logo: assets/images/Celesta.svg
  favicon: assets/images/Ce.svg

  palette:
    #- media: "(prefers-color-scheme: light)"
    #  scheme: celestadoc-light
    #  toggle:
    #    icon: material/brightness-7 
    #    name: Switch to dark mode

    #- media: "(prefers-color-scheme: dark)"
      scheme: celestadoc-dark
    #  toggle:
    #    icon: material/brightness-4
    #    name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - navigation.instant
    - navigation.indexes
    - navigation.footer
    - navigation.expand

    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy

    - search.highlight
    - search.suggest
    - toc.follow

  font:
    text: Figtree
    code: Overpass Mono

extra_css:
  - assets/themes/celestadoc.css
  - assets/themes/colors.css
  - assets/themes/page.css
  - assets/themes/home.css
  - assets/themes/code.css
  - assets/themes/admonition.css

nav:
  - Home: index.md
  - Learning:
    - Get Started: Learning/index.md
    - Downloading: Learning/Downloading.md
    - Contributing: Learning/Contributing.md

    - Core Concepts:
      - Components: Core Concepts/Components.md


markdown_extensions:
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.details
  - admonition
  - attr_list
  - md_in_html